export const SEQUELIZE = 'SEQUELIZE';
export const BOOK_REPOSITORY = 'BOOK_REPOSITORY';
export const MEMBER_REPOSITORY = 'MEMBER_REPOSITORY';
export const BOOK_MEMBER_REPOSITORY = 'BOOK_MEMBER_REPOSITORY';